# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d323913398b1319cd33216d16db0c6e38ca37f1c0bc0712541ecbca0a79526b2c5c9a6070cc95d747dc893291bdad75dde370eb6b925cbe066f7e6e0600ecce

test:
  secret_key_base: b750a285240de52dbf7369970ea580bc2cdd7ff28df53efbfecf703491715e320acbdfaeb716b7a14632f9cba979b5aa6534d6dc09a9b292ca2ad66d8dd81754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
